### ISSUE TITLE
ffbinaries.com is down

### ISSUE THREAD

**Issue by OClement** [vot/ffbinaries-node#20]
Hi,

Seems like ffbinaries.com is down right now
It would be a good idea to enable proper caching on cloudflare?
Our app build depends on this to work...

**Comment by vot** [comment]
Hi @OClement, sorry about this and thanks for the report. It's back up now.

The server provider forced a scheduled restart and as a side effect a service which blocked outside traffic on the app boxes got restarted. I'll try to fix that permanently.
I'll also look at caching things properly in CloudFlare.

**Comment by OClement** [comment]
Great, thanks for the quick turn around!

O.
